### ISSUE TITLE
Edit command does not detect duplicate projects if the created date is different

### ISSUE THREAD

**Issue by pr4aveen** [AY2021S1-CS2103T-T10-1/tp#65]
The command run in both images was `edit 1 n/b`. The only difference between the two project `a`'s is the created date.

![image](https://user-images.githubusercontent.com/2839596/96203354-4577fd00-0f94-11eb-894e-e5a6d6af6c4b.png)

![image](https://user-images.githubusercontent.com/2839596/96203370-4f99fb80-0f94-11eb-9fe6-1d75ba9f271a.png)

Changing the created date makes the program avoid the following condition in `EditCommand.java`. 

![image](https://user-images.githubusercontent.com/2839596/96203489-9982e180-0f94-11eb-8ac6-72113522dcd9.png)

Is this something that needs to be fixed?

**Comment by claracheong4** [comment]
I thought that this was the desired behaviour? 
For 2 projects to be considered as duplicate, it needs to be created on the same date.

**Comment by kkangs0226** [comment]
I think we should exclude the created date attribute when we are comparing two projects because it should not be an important attribute of the project? For example if I created this project yesterday and I forgot about it, and I make another entry today that has the exact same content, it should still be considered as a duplicate. What do the others think?

**Comment by boundtotheearth** [comment]
Yea I don't think created date should be a considered
